import type { Metadata } from "next";

import { NextUIProvider } from "@nextui-org/react";
import { Montserrat } from "next/font/google";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

import "./globals.css";
import ScrollToTopButton from "@/components/ScrollToTop";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NextUIProvider>
          <section className="text-balance min-h-screen container">
            {children}
            <ScrollToTopButton />
          </section>
        </NextUIProvider>
      </body>
    </html>
  );
}